version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    depends_on:
      - db  
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app_db
    volumes:
      - pg_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pg_data: